# Base16 VS Code Dark Theme
# Based on VS Code Dark theme colors
# Author: Shane Jarvie

scheme: "VS Code Dark"
author: "Shane Jarvie"

base00: "1e1e1e" # Default Background
base01: "262626" # Lighter Background (Used for status bars, line number and folding marks)
base02: "3c3c3c" # Selection Background
base03: "6a9955" # Comments, Invisibles, Line Highlighting
base04: "808080" # Dark Foreground (Used for status bars)
base05: "d4d4d4" # Default Foreground, Caret, Delimiters, Operators
base06: "e5e5e5" # Light Foreground (Not often used)
base07: "ffffff" # Light Background (Not often used)
base08: "f44747" # Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
base09: "ffcc02" # Integers, Boolean, Constants, XML Attributes, Markup Link Url
base0A: "e5e510" # Classes, Markup Bold, Search Text Background
base0B: "0dbc79" # Strings, Inherited Class, Markup Code, Diff Inserted
base0C: "11a8cd" # Support, Regular Expressions, Escape Characters, Markup Quotes
base0D: "2472c8" # Functions, Methods, Attribute IDs, Headings
base0E: "bc3fbc" # Keywords, Storage, Selector, Markup Italic, Diff Changed
base0F: "d670d6" # Deprecated, Opening/Closing Embedded Language Tags